name:                ananamer
version:             0.1.0.0
github:              "MisterEggnog/namegener"
license:             GPL-3.0-only
author:              "Baldwin, Josiah"
maintainer:          "12803156+MisterEggnog@users.noreply.github.com"
copyright:           "2021 Baldwin, Josiah"
build-type: Configure

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/MisterEggnog/namegener#readme>

dependencies:
- base >= 4.7 && < 5
- random
- random-shuffle
- sort
- sqlite-simple
- text

default-extensions:
- OverloadedStrings

library:
  source-dirs: src

executables:
  ananamer-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ananamer

tests:
  ananamer-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ananamer
    - HUnit
    - containers
